title : Course Site for Bush 631 -- Spring 2022
author :
  name : Rotem Dvir
  email : rdvir@tamu.edu
  github : rotemdvir
  twitter : nil
  feedburner : nil

markdown: kramdown

theme: jekyll-theme-cayman
